# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe8c42ce74fc3a6273fa5eb5d32d74a00d1fb499122420f5cc6d30913dfc083be6abb232faf827fc94981f7406c7508bbac5c5dcfeff747b121419c4b7745fe

test:
  secret_key_base: 2255199f9e240b722a4756ecacb11cf75438e0806232391737bf882139dcd8185abafc156d17867e85b3ccef22c4369816fd3a38b8b92491586f5ba95b136310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
